# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
$certs_path = "./certs"
$profiles_path = "./profiles"
$username = "awhearry@gmail.com"
$app_identifier = "com.codeinetech.Odeon"
$app_identifier_beta = "com.codeinetech.Odeon-Beta"
$app_identifier_dev = "com.codeinetech.Odeon-Dev"

default_platform(:ios)

platform :ios do
	before_all do
		update_fastlane
		ensure_git_status_clean(
			show_uncommitted_changes: true,
			show_diff: true
		)
		git_pull
	end

	desc "Beta realeases"
	lane :beta do
		cert(
			username: $username,
			output_path: $certs_path
		)
		sigh(
			app_identifier: $app_identifier,
			output_path: $profiles_path,
			force: true
		)
		register_devices(devices_file: "devices.txt")
		gym(silent: true, export_method: "app-store", configuration: "Beta")
		upload_to_testflight(
			username: $username,
			app_identifier: $app_identifier,
			itc_provider: "HZQ3ZGBLE6",
			beta_app_feedback_email: "allen@codeinecoding.com",
			distribute_external: true,
			groups: ["InnerCircle", "SocialMediaTesters"],
			notify_external_testers: true,
			reject_build_waiting_for_review: true
			)
		increment_build_number(xcodeproj: "Odeon.xcodeproj")
		commit_version_bump(
			message: 'Build Version Bump by fastlane',
			xcodeproj: "Odeon.xcodeproj",
			force: true
			)
		add_git_tag(grouping: "beta")
		push_to_git_remote
		push_git_tags
	end

	lane :push do
		push_to_git_remote
	end

	lane :development do
		register_devices(devices_file: "devices.txt")
  	# match(type: "development", force_for_new_devices: false)
  end

  lane :screenshots do 
  	snapshot(
  		app_identifier: $app_identifier,
  		clear_previous_screenshots: true
  	)
  end

  lane :release do
  	produce(
  		username: $username,
  		app_identifier: $app_identifier,
  		app_name: "Odeon Quotes",
  		language: "English",
  		app_version: "1.1",
  		)
  end
end
